
import java.awt.Color;
import java.awt.Graphics;
import javafx.scene.control.ButtonBar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class background extends javax.swing.JPanel {

    /**
     * Creates new form background
     */
    Column[] c;
    boolean conchoi=true;
    boolean conchoichim=true;
    Chim cu;
    int diem=0;
    int time=50;
    int timeDown=70;
    public background() {
        init();
        initComponents();
        time=50;
        t.start();
        t2.start();
        lbDiem.setText("0");
        
    }
    Thread t=new Thread(new Runnable(){

        @Override
        public void run() {
            while(conchoi){
                for(int i=0;i<3;i++){
                    if(c[i].x==100){
                        diem++;
                        lbDiem.setText(""+diem);
                    }
                    
                }
                for (Column column : c) {
                    column.x=column.x-10;
                }
                if(isGameOver()){
                    conchoi=false;
                    
                    if(JOptionPane.showConfirmDialog(null, " Your Score: "+diem+"\nchoi lai ko")==JOptionPane.YES_OPTION){
                        conchoi=true;                     
                        init();
                        repaint();
                    }
                    diem=0;
                    lbDiem.setText("0");
                    time=50;
                    timeDown=70;
                }
                for (Column column : c) {
                    if(column.x==0)
                        column.x=1000;
                }
                repaint();
                try {
                    if(diem==10 && diem>0){
                        time=40;
                        timeDown=50;
                        
                    }
                    System.out.println(time+" "+timeDown);
                    Thread.sleep(time);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
            
     });
    
    Thread t2=new Thread(new Runnable(){

        @Override
        public void run() {
            while(conchoichim){
                cu.y=cu.y+4;
               
                repaint();
                try {
                    t2.sleep(timeDown);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
            
     });
            
            
            
            
            

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        this.setSize(2000, 1000);
        this.setBackground(Color.CYAN);
        for (Column column : c) {
            column.drawColumn(g);
        }
        if(diem==10){
            cu.setFilename("phoenix.jpg");
        }
        cu.drawChim(g);
    }
    
    void init(){
        c=new Column[6];
        c[0]=new Column(Color.GREEN, 300, 0, 100, 250);
        c[1]=new Column(Color.GREEN, 600, 0, 80, 350);
        c[2]=new Column(Color.GREEN, 900, 0, 120, 250);
        
        c[3]=new Column(Color.GREEN, 300, 400, 100, 650);
        c[4]=new Column(Color.GREEN, 600, 500, 80, 500);
        c[5]=new Column(Color.GREEN, 900, 400, 120, 650);
        cu=new Chim("Flappybird.png", 100, 450, 70, 50);
        if(diem==10 && diem>0){
            time-=10;
            timeDown-=10;
        }
    }
    public boolean isGameOver(){
        for (Column column : c) {
            if(column.intersects(cu))//giao nhau
                return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDiem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lbDiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDiem.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Point:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(563, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap(495, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lbDiem;
    // End of variables declaration//GEN-END:variables
}
